[build]
  base = "frontend/"
  command = "ng build"
  publish = "dist/frontend"

[build.environment]
  NG_BUILD_AOT = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "ng build --configuration production"
